version: "3.9"

services:
  backend:
    build: 
      context: ./backend
    container_name: notevader-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5001"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: notevader-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
